# Generated by Django 2.1.5 on 2019-02-04 15:14

import commons.custom_model_fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioupload',
            name='direct_url',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='audioupload',
            name='file',
            field=commons.custom_model_fields.VariableStorageFileField(blank=True, null=True, upload_to='audio_records'),
        ),
    ]
