# Generated by Django 2.1.5 on 2019-02-05 02:10

import commons.custom_model_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_auto_20190204_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('file_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='audioupload',
            name='file',
            field=commons.custom_model_fields.VariableStorageFileField(blank=True, null=True, upload_to='audio.AudioFile/content/file_name/mime_type'),
        ),
    ]
