# Generated by Django 2.1.5 on 2019-02-05 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0003_auto_20190205_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioupload',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
