# Generated by Django 2.1.5 on 2019-02-05 04:06

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0004_auto_20190205_0219'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AudioFile',
        ),
        migrations.RemoveField(
            model_name='audioupload',
            name='file',
        ),
        migrations.AddField(
            model_name='audioupload',
            name='s3_file',
            field=s3direct.fields.S3DirectField(blank=True, null=True),
        ),
    ]
