# Generated by Django 2.1.5 on 2019-02-05 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0005_auto_20190205_0406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audioupload',
            old_name='uuid',
            new_name='audio_uuid',
        ),
    ]
